### ISSUE TITLE
Update angular-cli@v1.0.0-beta.14

### ISSUE THREAD

**Issue by mhmmdd** [hdjirdeh/angular2-hn#4]
Great app but It doesn't work with **angular-cli@v1.0.0-beta.14** can you update?

Gives this output: 

```
It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and includes a lot of improvements, include a simpler workflow, a faster build and smaller bundles.

To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12
```

**Comment by hdjirdeh** [comment]
Done, just updated to beta.14 :+1:

**Comment by mhmmdd** [comment]
That's great! This is working now, thanks :+1: 

Only I need to install this dependency **process-nextick-args**

**Comment by hdjirdeh** [comment]
Awesome, glad to hear it's working :)

And really eh? Hmm didn't have to install that myself. Does it error asking you to install it?

**Comment by mhmmdd** [comment]
Yep, It gives this error (_Cannot find module 'process-nextick-args'_) in [here](https://github.com/sass/node-sass/issues/1268).
```cmd
npm install --save process-nextick-args
```
Fixes this issue.

**Comment by hdjirdeh** [comment]
Okay thanks for letting me know mate. Interesting that I didn't get the error, but at least it was a quick fix 👍🏽
